//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelApi.GlobalEntity
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Otel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otel()
        {
            this.Ticket = new HashSet<Ticket>();
            this.Client = new HashSet<Client>();
            this.Room = new HashSet<Room>();
        }
    
        public int ID { get; set; }
        public int NameOtelID { get; set; }
        public int AddressOfOtelID { get; set; }
        public int ImageID { get; set; }
        public Nullable<int> DiscriptionID { get; set; }

        [JsonIgnore]
        public virtual AddressOfOtel AddressOfOtel { get; set; }
        [JsonIgnore]
        public virtual Discription Discription { get; set; }
        [JsonIgnore]
        public virtual ImageOfOtel ImageOfOtel { get; set; }
        [JsonIgnore]
        public virtual NameOtel NameOtel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Ticket> Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Client> Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Room> Room { get; set; }
    }
}
