//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelApi.GlobalEntity
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public int TypeRoomID { get; set; }
        public int Number { get; set; }
        public int PriceID { get; set; }
        public Nullable<int> OtelID { get; set; }

        [JsonIgnore]
        public virtual Otel Otel { get; set; }
        public virtual Price Price { get; set; }
        public virtual TypeRoom TypeRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Order> Order { get; set; }
    }
}
